[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "SynRst"
  [en.params]
    tagline = "Security Research and Technical Notes"

[zh-CN]
  languageName = "中文"
  languageCode = "zh-CN"
  weight = 1
  title = "synack"
  [zh-CN.params]
    tagline = "一个专注于文本的博客主题"