name: Deploy to Github Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Blog
      - name: Checkout Blog
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Vault Obsidian
      - name: Checkout Vault
        uses: actions/checkout@v4
        with:
          repository: SynAck-rm-f/vault-obsidian-backup
          path: vault-obsidian-backup

      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-hugo

      - name: Setup Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24.2"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Debug
        run: |
          pwd
          ls -la
          ls -la vault
          ls -la "vault/01-Write UP Box & Blog"

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
